name: Fly.io Deploy

on:
  pull_request:
    types: [closed]
    branches: ["master"]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      if: github.event.pull_request.merged == true
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: User flyctl-actions Template
          uses: superfly/flyctl-actions/setup-flyctl@master

        - name: Deploy
          run: flyctl deploy
