name: Fly.io Deploy

on:
  pull_request:
    types: [closed]
    branches: ["master"]
    
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: todo-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | sh

      - name: Login to flyctl
        run: /home/runner/.fly/bin/flyctl auth login --access-token "${FLY_API_TOKEN}"

      - name: Deploy app
        run: /home/runner/.fly/bin/flyctl deploy --app "${FLY_APP_NAME}"
